import alpacafinance from "../../assets/icons/tokens/alpacafinance.svg";
import ariva from "../../assets/icons/tokens/ariva.svg";
import biconomy from "../../assets/icons/tokens/biconomy.svg";
import celolight from "../../assets/icons/tokens/celolight.svg";
import daomaker from "../../assets/icons/tokens/daomaker.svg";
import dodoblack from "../../assets/icons/tokens/dodoblack.svg";
import envision from "../../assets/icons/tokens/envision.svg";
import epnspush from "../../assets/icons/tokens/epnspush.svg";
import galileo from "../../assets/icons/tokens/galileo.svg";
import tron from "../../assets/icons/tokens/tron.svg";
import xdbdigitalbits from "../../assets/icons/tokens/xdbdigitalbits.svg";
import voltinu from "../../assets/icons/tokens/voltinu.svg";

import bibox from "../../assets/icons/exchanges/bibox.svg";
import binance from "../../assets/icons/exchanges/binance.svg";
import bitbns from "../../assets/icons/exchanges/bitbns.svg";
import bitfinex from "../../assets/icons/exchanges/bitfinex.svg";
import bitget from "../../assets/icons/exchanges/bitget.svg";
import bitkub from "../../assets/icons/exchanges/bitkub.svg";
import bitmex from "../../assets/icons/exchanges/bitmex.svg";
import brine from "../../assets/icons/exchanges/brine.svg";
import bybit from "../../assets/icons/exchanges/bybit.svg";
import coinbase from "../../assets/icons/exchanges/coinbase.svg";
import coindcx from "../../assets/icons/exchanges/coindcx.svg";
import coinswitch from "../../assets/icons/exchanges/coinswitch.svg";
import crypto from "../../assets/icons/exchanges/crypto.svg";
import cryptofacilities from "../../assets/icons/exchanges/cryptofacilities.svg";
import deribit from "../../assets/icons/exchanges/deribit.svg";
import gateio from "../../assets/icons/exchanges/gateio.svg";
import huobi from "../../assets/icons/exchanges/huobi.svg";
import indodax from "../../assets/icons/exchanges/indodax.svg";
import kucoin from "../../assets/icons/exchanges/kucoin.svg";
import lcx from "../../assets/icons/exchanges/lcx.svg";
import mexcglobal from "../../assets/icons/exchanges/mexcglobal.svg";
import okex from "../../assets/icons/exchanges/okex.svg";
import opnxwhite from "../../assets/icons/exchanges/opnxwhite.svg";
import unocoin from "../../assets/icons/exchanges/unocoin.svg";
import valr from "../../assets/icons/exchanges/valr.svg";
import wazirx from "../../assets/icons/exchanges/wazirx.svg";
import coinstore from "../../assets/icons/exchanges/coinstore.svg";
import falconx from "../../assets/icons/exchanges/falconx.svg";
import exmo from "../../assets/icons/exchanges/exmo.svg";

export const allExchanges = [
  { exchange: bibox },
  { exchange: binance },
  { exchange: bitbns },
  { exchange: bitfinex },
  { exchange: bitget },
  { exchange: bitkub },
  { exchange: bitmex },
  { exchange: brine },
  { exchange: bybit },
  { exchange: coinbase },
  { exchange: coindcx },
  { exchange: coinswitch },
  { exchange: crypto },
  { exchange: cryptofacilities },
  { exchange: deribit },
  { exchange: gateio },
  { exchange: huobi },
  { exchange: indodax },
  { exchange: kucoin },
  { exchange: lcx },
  { exchange: mexcglobal },
  { exchange: okex },
  { exchange: opnxwhite },
  { exchange: unocoin },
  { exchange: valr },
  { exchange: wazirx },
  { exchange: coinstore },
  { exchange: falconx },
  { exchange: exmo },
];

export const allTokens = [
  { token: alpacafinance },
  { token: ariva },
  { token: biconomy },
  { token: celolight },
  { token: daomaker },
  { token: dodoblack },
  { token: envision },
  { token: epnspush },
  { token: galileo },
  { token: tron },
  { token: xdbdigitalbits },
  { token: voltinu },
];
